### ISSUE TITLE
PacketHandler sharedSecret

### ISSUE THREAD

**Issue by SebZar** [vforteli/Flexinets.Radius.RadiusServer#16]
Hi,
I've added a packet handler with a shared secret and everythings works fine.

When I change the shared secret on my test client the handler is still triggered. The secret for the handler is not checked against the secret the client sends and the request triggers the handler.

Is this intended or a bug?

Is there an option to dismiss a request, when the shared secret is not matching?

Is it possible to get the shared secret which is sent in the clients request?

Thanks

**Comment by vforteli** [comment]
If it is an access request, then yes, it should hit the handler. However if a response is sent in return the response authenticator would be invalid. Also, in case you would try to validate a simple user-password attribute in the handler it would not match because its encrypted with the wrong secret.
Other packet types contain request authenticators (and message authenticators in some cases) that ensures packets with invalid secrets are dropped before hitting the handler

Disclaimer: the cryptographic features of radius have been broken years ago, so one shouldnt rely on them alone anyway.

**Comment by SebZar** [comment]
Yes, it is the access request. Thanks for the clearification.
